#pragma once
#ifndef CN_H
#define CN_H 1
#define CN_S_1 "文件输出的无窗口的原神祈愿模拟器 V2.5.16"
#define CN_S_2 "作者: Jirehlov Research"
#define CN_S_3 "开源于GitHub: Jirehlov_Genshin-Impact-Wish-Simulator-Fileout"
#define CN_S_4 "GPL-3.0 License"
#define CN_S_62 "默认空数据"
#define CN_S_63 "好运参考值: "
#define CN_S_72 "输入不合理!"
#define CN_S_73 "你总共抽了 "
#define CN_S_74 " 发。"
#define CN_S_75 "五星角色或武器:   "
#define CN_S_76 "四星角色或武器:   "
#define CN_S_77 "五星角色 : 五星武器 : 四星角色 : 四星武器   "
#define CN_S_78 "连续非五星最高纪录:   "
#define CN_S_79 " 发。首次发生在第 "
#define CN_S_80 " 个保底单元, 即第 "
#define CN_S_81 " 次祈愿。"
#define CN_S_82 "连续非五星最低纪录:   "
#define CN_S_83 "连续非五星平均祈愿数:   "
#define CN_S_84 " 秒过去了。"
#define CN_S_85 "本次祈愿结果如下:"
#define CN_S_86 "本次祈愿开始于:  "
#define CN_S_87 "本次祈愿结束于:  "
#define CN_S_88 "四星角色或武器概率分布"
#define CN_S_89 "五星角色或武器概率分布"
#define CN_E_1 "kind 不合理! 错误码: 1"
#define CN_E_2 "fate_weapon 不合理! 错误码: 2"
#define CN_E_3 "resultt 不合理! 错误码: 3"
#define CN_E_4 "resultu 不合理! 错误码: 4"
#define CN_E_5 "chosen_event 不合理! 错误码: 5"
#define CN_E_6 "quit 不合理! 错误码: 6"
#define CN_E_7 "chosen_banner 不合理! 错误码: 7"
#define CN_E_8 "five_count 不合理! 错误码: 8"
#define CN_E_11 "arguments错误! 正确格式为: 卡池类型编号 活动类型编号 祈愿数量"
#endif