#pragma once
#ifndef CN_H
#define S_1 "原神祈愿模拟器（无窗口）V2.5.4"
#define S_2 "作者: Jirehlov Research"
#define S_3 "开源于GitHub: Jirehlov_Genshin-Impact-Wish-Simulator-Fileout"
#define S_4 "GPL-3.0 License"
#define S_62 "默认空数据"
#define S_63 "好运参考值: "
#define S_72 "输入不合理!"
#define S_73 "你总共抽了 "
#define S_74 " 发。"
#define S_75 "五星角色或武器:   "
#define S_76 "四星角色或武器:   "
#define S_77 "五星角色 : 五星武器 : 四星角色 : 四星武器   "
#define S_78 "连续非五星最高纪录:   "
#define S_79 " 发。首次发生在第 "
#define S_80 " 个保底单元, 即第 "
#define S_81 " 次祈愿。"
#define S_82 "连续非五星最低纪录:   "
#define S_83 "连续非五星平均祈愿数:   "
#define S_84 " 秒过去了。"
#define S_85 "本次祈愿结果如下:"
#define S_86 "本次祈愿开始于:  "
#define S_87 "本次祈愿结束于:  "
#define S_88 "四星角色或武器概率分布"
#define S_89 "五星角色或武器概率分布"
#define C_0 "霆霓快雨·刻晴（雷）"
#define C_1 "星天水镜·莫娜（水）"
#define C_2 "冻冻回魂夜·七七（冰）"
#define C_3 "晨曦的暗面·迪卢克（火）"
#define C_4 "蒲公英骑士·琴（风）"
#define C_5 "弓·阿莫斯之弓"
#define C_6 "弓·天空之翼"
#define C_7 "法器·四风原典"
#define C_8 "法器·天空之卷"
#define C_9 "长柄武器·和璞鸢"
#define C_10 "长柄武器·天空之脊"
#define C_11 "双手剑·狼的末路"
#define C_12 "双手剑·天空之傲"
#define C_13 "单手剑·天空之刃"
#define C_14 "单手剑·风鹰剑"
#define C_15 "棘冠恩典·罗莎莉亚（冰）"
#define C_16 "燥热旋律·辛焱（火）"
#define C_17 "无害甜度·砂糖（风）"
#define C_18 "猫尾特调·迪奥娜（冰）"
#define C_19 "雪融有踪·重云（冰）"
#define C_20 "未受勋之花·诺艾尔（岩）"
#define C_21 "命运试金石·班尼特（火）"
#define C_22 "断罪皇女！！·菲谢尔（雷）"
#define C_23 "掩月天权·凝光（岩）"
#define C_24 "少年春衫薄·行秋（水）"
#define C_25 "无冕的龙王·北斗（雷）"
#define C_26 "万民百味·香菱（火）"
#define C_27 "飞行冠军·安柏（火）"
#define C_28 "狼少年·雷泽（雷）"
#define C_29 "寒风剑士·凯亚（冰）"
#define C_30 "闪耀偶像·芭芭拉（水）"
#define C_31 "蔷薇魔女·丽莎（雷）"
#define C_32 "弓·弓藏"
#define C_33 "弓·祭礼弓"
#define C_34 "弓·绝弦"
#define C_35 "弓·西风猎弓"
#define C_36 "法器·昭心"
#define C_37 "法器·祭礼残章"
#define C_38 "法器·流浪乐章"
#define C_39 "法器·西风秘典"
#define C_40 "长柄武器·西风长枪"
#define C_41 "长柄武器·匣里灭辰"
#define C_42 "双手剑·雨裁"
#define C_43 "双手剑·祭礼大剑"
#define C_44 "双手剑·钟剑"
#define C_45 "双手剑·西风大剑"
#define C_46 "单手剑·匣里龙吟"
#define C_47 "单手剑·祭礼剑"
#define C_48 "单手剑·笛剑"
#define C_49 "单手剑·西风剑"
#define C_50 "弓·猎弓"
#define C_51 "弓·神射手之誓"
#define C_52 "弓·鸦羽弓"
#define C_53 "法器·翡玉法球"
#define C_54 "法器·讨龙英杰谭"
#define C_55 "法器·魔导绪论"
#define C_56 "长柄武器·黑缨枪"
#define C_57 "双手剑·以理服人"
#define C_58 "双手剑·沐浴龙血的剑"
#define C_59 "双手剑·铁影阔剑"
#define C_60 "单手剑·飞天御剑"
#define C_61 "单手剑·黎明神剑"
#define C_62 "单手剑·冷刃"
#define C_63 "风色诗人·温迪（风）"
#define C_64 "逃跑的太阳·可莉（火）"
#define C_65 "「公子」·达达利亚（水）"
#define C_66 "尘世闲游·钟离（岩）"
#define C_67 "白垩之子·阿贝多（岩）"
#define C_68 "循循守月·甘雨（冰）"
#define C_69 "护法夜叉·魈（风）"
#define C_70 "雪霁梅香·胡桃（火）"
#define C_71 "智明无邪·烟绯（火）"
#define C_72 "浪沫的旋舞·优菈（冰）"
#define C_73 "法器·尘世之锁"
#define C_74 "长柄武器·贯虹之槊"
#define C_75 "双手剑·无工之剑"
#define C_76 "单手剑·斫峰之刃"
#define C_77 "单手剑·磐岩结绿"
#define C_78 "长柄武器·护摩之杖"
#define C_79 "双手剑·千岩古剑"
#define C_80 "长柄武器·千岩长枪"
#define C_81 "弓·终末嗟叹之诗"
#define C_82 "单手剑·暗巷闪光"
#define C_83 "法器·暗巷的酒与诗"
#define C_84 "弓·暗巷猎手"
#define C_85 "双手剑·松籁响起之时"
#define C_86 "红叶逐荒波·枫原万叶（风）"
#define C_87 "单手剑·苍古自由之誓"
#define C_88 "弓·幽夜华尔兹"
#define C_89 "白鹭霜华·神里绫华（冰）"
#define C_90 "琉焰华舞·宵宫（火）"
#define C_91 "忍里之貉·早柚（风）"
#define C_92 "单手剑·雾切之回光"
#define C_93 "弓·飞雷之弦振"
#define C_94 "真珠之智·珊瑚宫心海（水）"
#define C_95 "黑羽鸣镝·九条裟罗（雷）"
#define C_96 "一心净土·雷电将军（雷）"
#define C_97 "长柄武器·薙草之稻光"
#define C_98 "法器·不灭月华"
#define C_99 "浮世笑百姿·八重神子（雷）"
#define C_100 "渡来介者·托马（火）"
#define C_101 "弓·冬极白星"
#define C_102 "弓·曚云之月"
#define C_103 "长柄武器·断浪长鳍"
#define C_104 "双手剑·恶玉丸"
#define C_105 "花坂豪快·荒泷一斗（岩）"
#define C_106 "戎犬锵锵·五郎（岩）"
#define C_107 "双手剑·赤角石溃杵"
#define C_108 "红毹婵娟·云堇（岩）"
#define C_109 "孤辰茕怀·申鹤（冰）"
#define C_110 "长柄武器·息灾"
#define C_111 "磐祭叶守·神里绫人（水）"
#define C_112 "法器·神乐之真意"
#define X_0 "刻晴"
#define X_1 "莫娜"
#define X_2 "七七"
#define X_3 "迪卢克"
#define X_4 "琴"
#define X_5 "阿莫斯之弓"
#define X_6 "天空之翼"
#define X_7 "四风原典"
#define X_8 "天空之卷"
#define X_9 "和璞鸢"
#define X_10 "天空之脊"
#define X_11 "狼的末路"
#define X_12 "天空之傲"
#define X_13 "天空之刃"
#define X_14 "风鹰剑"
#define X_15 "罗莎莉亚"
#define X_16 "辛焱"
#define X_17 "砂糖"
#define X_18 "迪奥娜"
#define X_19 "重云"
#define X_20 "诺艾尔"
#define X_21 "班尼特"
#define X_22 "菲谢尔"
#define X_23 "凝光"
#define X_24 "行秋"
#define X_25 "北斗"
#define X_26 "香菱"
#define X_27 "安柏"
#define X_28 "雷泽"
#define X_29 "凯亚"
#define X_30 "芭芭拉"
#define X_31 "丽莎"
#define X_32 "弓藏"
#define X_33 "祭礼弓"
#define X_34 "绝弦"
#define X_35 "西风猎弓"
#define X_36 "昭心"
#define X_37 "祭礼残章"
#define X_38 "流浪乐章"
#define X_39 "西风秘典"
#define X_40 "西风长枪"
#define X_41 "匣里灭辰"
#define X_42 "雨裁"
#define X_43 "祭礼大剑"
#define X_44 "钟剑"
#define X_45 "西风大剑"
#define X_46 "匣里龙吟"
#define X_47 "祭礼剑"
#define X_48 "笛剑"
#define X_49 "西风剑"
#define X_50 "猎弓"
#define X_51 "神射手之誓"
#define X_52 "鸦羽弓"
#define X_53 "翡玉法球"
#define X_54 "讨龙英杰谭"
#define X_55 "魔导绪论"
#define X_56 "黑缨枪"
#define X_57 "以理服人"
#define X_58 "沐浴龙血的剑"
#define X_59 "铁影阔剑"
#define X_60 "飞天御剑"
#define X_61 "黎明神剑"
#define X_62 "冷刃"
#define X_63 "温迪"
#define X_64 "可莉"
#define X_65 "达达利亚"
#define X_66 "钟离"
#define X_67 "阿贝多"
#define X_68 "甘雨"
#define X_69 "魈"
#define X_70 "胡桃"
#define X_71 "烟绯"
#define X_72 "优菈"
#define X_73 "尘世之锁"
#define X_74 "贯虹之槊"
#define X_75 "无工之剑"
#define X_76 "斫峰之刃"
#define X_77 "磐岩结绿"
#define X_78 "护摩之杖"
#define X_79 "千岩古剑"
#define X_80 "千岩长枪"
#define X_81 "终末嗟叹之诗"
#define X_82 "暗巷闪光"
#define X_83 "暗巷的酒与诗"
#define X_84 "暗巷猎手"
#define X_85 "松籁响起之时"
#define X_86 "枫原万叶"
#define X_87 "苍古自由之誓"
#define X_88 "幽夜华尔兹"
#define X_89 "神里绫华"
#define X_90 "宵宫"
#define X_91 "早柚"
#define X_92 "雾切之回光"
#define X_93 "飞雷之弦振"
#define X_94 "珊瑚宫心海"
#define X_95 "九条裟罗"
#define X_96 "雷电将军"
#define X_97 "薙草之稻光"
#define X_98 "不灭月华"
#define X_99 "八重神子"
#define X_100 "托马"
#define X_101 "冬极白星"
#define X_102 "曚云之月"
#define X_103 "断浪长鳍"
#define X_104 "恶玉丸"
#define X_105 "荒泷一斗"
#define X_106 "五郎"
#define X_107 "赤角石溃杵"
#define X_108 "云堇"
#define X_109 "申鹤"
#define X_110 "息灾"
#define X_111 "神里绫人"
#define X_112 "神乐之真意"
#define E_1 "kind 不合理! 错误码: 1"
#define E_2 "fate_weapon 不合理! 错误码: 2"
#define E_3 "resultt 不合理! 错误码: 3"
#define E_4 "resultu 不合理! 错误码: 4"
#define E_5 "chosen_event 不合理! 错误码: 5"
#define E_6 "quit 不合理! 错误码: 6"
#define E_7 "chosen_banner 不合理! 错误码: 7"
#define E_8 "five_count 不合理! 错误码: 8"
#define E_11 "arguments错误! 正确格式为: 卡池类型编号 活动类型编号 祈愿数量"
#endif