#pragma once
#ifndef EN_H
#define EN_H 1
#define S_1 "WELCOME TO GENSHIN IMPACT WISH SIMULATOR Fileout V2.5.16"
#define S_2 "by Jirehlov Research"
#define S_3 "Source code available on GitHub: Jirehlov_Genshin-Impact-Wish-Simulator-Fileout"
#define S_4 "GPL-3.0 License"
#define S_62 "Default"
#define S_63 "Luckiness: "
#define S_72 "Incorrect input!"
#define S_73 "In total, You have pulled "
#define S_74 " wishes."
#define S_75 "5-stars:   "
#define S_76 "4-stars:   " 
#define S_77 "5-star-characters : 5-star-weapons : 4-star-characters : 4-star-weapons   "
#define S_78 "max 5-star pity:   "
#define S_79 " initially at "
#define S_80 "-th non-5-star  "
#define S_81 "-th wishes"
#define S_82 "min 5-star pity:   "
#define S_83 "ave 5-star pity:   "
#define S_84 " seconds elapsed."
#define S_85 "You get:"
#define S_86 "Started at:  "
#define S_87 "Ended at:  "
#define S_88 "4-stars Distribution"
#define S_89 "5-stars Distribution"
#define E_1 "Unexpected kind! Error code: 1"
#define E_2 "Unexpected fate_weapon! Error code: 2"
#define E_3 "Unexpected resultt! Error code: 3"
#define E_4 "Unexpected resultu! Error code: 4"
#define E_5 "Unexpected chosen_event! Error code: 5"
#define E_6 "Unexpected quit! Error code: 6"
#define E_7 "Unexpected chosen_banner! Error code: 7"
#define E_8 "Unexpected five_count! Error code: 8"
#define E_11 "Arguments error! Usage: chosen_banner chosen_event wishes_number"
#endif