#pragma once
#ifndef EN_H
#define EN_H 1
#define EN_S_1 "WELCOME TO GENSHIN IMPACT WISH SIMULATOR Fileout V2.6.2"
#define EN_S_2 "by Jirehlov Research"
#define EN_S_3 "Source code available on GitHub: Jirehlov_Genshin-Impact-Wish-Simulator-Fileout"
#define EN_S_4 "GPL-3.0 License"
#define EN_S_62 "Default"
#define EN_S_63 "Luckiness: "
#define EN_S_72 "Incorrect input!"
#define EN_S_73 "In total, You have pulled "
#define EN_S_74 " wishes."
#define EN_S_75 "5-stars:   "
#define EN_S_76 "4-stars:   " 
#define EN_S_77 "5-star-characters : 5-star-weapons : 4-star-characters : 4-star-weapons   "
#define EN_S_78 "max 5-star pity:   "
#define EN_S_79 " initially at "
#define EN_S_80 "-th non-5-star  "
#define EN_S_81 "-th wishes"
#define EN_S_82 "min 5-star pity:   "
#define EN_S_83 "ave 5-star pity:   "
#define EN_S_84 " seconds elapsed."
#define EN_S_85 "You get:"
#define EN_S_86 "Started at:  "
#define EN_S_87 "Ended at:  "
#define EN_S_88 "4-stars Distribution"
#define EN_S_89 "5-stars Distribution"
#define EN_E_1 "Unexpected kind! Error code: 1"
#define EN_E_2 "Unexpected fate_weapon! Error code: 2"
#define EN_E_3 "Unexpected resultt! Error code: 3"
#define EN_E_4 "Unexpected resultu! Error code: 4"
#define EN_E_5 "Unexpected chosen_event! Error code: 5"
#define EN_E_6 "Unexpected quit! Error code: 6"
#define EN_E_7 "Unexpected chosen_banner! Error code: 7"
#define EN_E_8 "Unexpected five_count! Error code: 8"
#define EN_E_11 "Arguments error! Usage: chosen_banner chosen_event wishes_number"
#endif