#pragma once
#ifndef EN_H
#define S_1 "WELCOME TO GENSHIN IMPACT WISH SIMULATOR Fileout V2.4.4"
#define S_2 "by Jirehlov Research"
#define S_3 "Source code available on GitHub: Jirehlov_Genshin-Impact-Wish-Simulator-Fileout"
#define S_4 "GPL-3.0 License"
#define S_62 "Default"
#define S_63 "Luckiness: "
#define S_72 "Incorrect input!"
#define S_73 "In total, You have pulled "
#define S_74 " wishes."
#define S_75 "5-stars:   "
#define S_76 "4-stars:   " 
#define S_77 "5-star-characters : 5-star-weapons : 4-star-characters : 4-star-weapons   "
#define S_78 "max 5-star pity:   "
#define S_79 " initially at "
#define S_80 "-th non-5-star  "
#define S_81 "-th wishes"
#define S_82 "min 5-star pity:   "
#define S_83 "ave 5-star pity:   "
#define S_84 " seconds elapsed."
#define S_85 "You get:"
#define S_86 "Started at:  "
#define S_87 "Ended at:  "
#define S_88 "4-stars Distribution"
#define S_89 "5-stars Distribution"
#define C_0 "\"Driving Thunder\" Keqing (Electro)"
#define C_1 "\"Astral Reflection\" Mona (Hydro)"
#define C_2 "\"Icy Resurrection\" Qiqi (Cryo)"
#define C_3 "\"The Dark Side of Dawn\" Diluc (Pyro)"
#define C_4 "\"Dandelion Knight\" Jean (Anemo)"
#define C_5 "Amos' Bow (Bow)"
#define C_6 "Skyward Harp (Bow)"
#define C_7 "Lost Prayer to the Sacred Winds (Catalyst)"
#define C_8 "Skyward Atlas (Catalyst)"
#define C_9 "Primordial Jade Winged-Spear (Polearm)"
#define C_10 "Skyward Spine (Polearm)"
#define C_11 "Wolf's Gravestone (Claymore)"
#define C_12 "Skyward Pride (Claymore)"
#define C_13 "Skyward Blade (Sword)"
#define C_14 "Aquila Favonia (Sword)"
#define C_15 "\"Thorny Benevolence\" Rosaria (Cryo)"
#define C_16 "\"Blazing Riff\" Xinyan (Pyro)"
#define C_17 "\"Harmless Sweetie\" Sucrose (Anemo)"
#define C_18 "\"Kätzlein Cocktail\" Diona (Cryo)"
#define C_19 "\"Frozen Ardor\" Chongyun (Cryo)"
#define C_20 "\"Chivalric Blossom\" Noelle (Geo)"
#define C_21 "\"Trial by Fire\" Bennett (Pyro)"
#define C_22 "\"Prinzessin der Verurteilung!\" Fischl (Electro)"
#define C_23 "\"Eclipsing Star\" Ningguang (Geo)"
#define C_24 "\"Juvenile Galant\" Xingqiu (Hydro)"
#define C_25 "\"Uncrowned Lord of the Ocean\" Beidou (Electro)"
#define C_26 "\"Exquisite Delicacy\" Xiangling (Pryo)"
#define C_27 "\"Gliding Champion\" Amber (Pryo)"
#define C_28 "\"Wolf Boy\" Razor (Electro)"
#define C_29 "\"Frostwind Swordsman\" Kaeya (Cryo)"
#define C_30 "\"Shining Idol\" Barbara (Hydro)"
#define C_31 "\"Witch of Purple Rose\" Lisa (Electro)"
#define C_32 "Rust (Bow)"
#define C_33 "Sacrificial Bow (Bow)"
#define C_34 "The Stringless (Bow)"
#define C_35 "Favonius Warbow (Bow)"
#define C_36 "Eye of Perception (Catalyst)"
#define C_37 "Sacrificial Fragments (Catalyst)"
#define C_38 "The Widsith (Catalyst)"
#define C_39 "Favonius Codex (Catalyst)"
#define C_40 "Favonius Lance (Polearm)"
#define C_41 "Dragon's Bane (Polearm)"
#define C_42 "Rainslasher (Claymore)"
#define C_43 "Sacrificial Greatsword (Claymore)"
#define C_44 "The Bell (Claymore)"
#define C_45 "Favonius Greatsword (Claymore)"
#define C_46 "Lion's Roar (Sword)"
#define C_47 "Sacrificial Sword (Sword)"
#define C_48 "The Flute (Sword)"
#define C_49 "Favonius Sword (Sword)"
#define C_50 "Slingshot (Bow)"
#define C_51 "Sharpshooter's Oath (Bow)"
#define C_52 "Raven Bow (Bow)"
#define C_53 "Emerald Orb (Catalyst)"
#define C_54 "Thrilling Tales of Dragon Slayers (Catalyst)"
#define C_55 "Magic Guide (Catalyst)"
#define C_56 "Black Tassel (Polearm)"
#define C_57 "Debate Club (Claymore)"
#define C_58 "Bloodtainted Greatsword (Claymore)"
#define C_59 "Ferrous Shadow (Claymore)"
#define C_60 "Skyrider Sword (Sword)"
#define C_61 "Harbinger of Dawn (Sword)"
#define C_62 "Cool Steel (Sword)"
#define C_63 "\"Windborne Bard\" Venti (Anemo)"
#define C_64 "\"Fleeing Sunlight\" Klee (Pyro)"
#define C_65 "\"Childe\" Tartaglia (Hydro)"
#define C_66 "\"Vago Mundo\" Zhongli (Geo)"
#define C_67 "\"Kreideprinz\" Albedo (Geo)"
#define C_68 "\"Plenilune Gaze\" Ganyu (Cryo)"
#define C_69 "\"Vigilant Yaksha\" Xiao (Anemo)"
#define C_70 "\"Fragrance in Thaw\" Hu Tao (Pryo)"
#define C_71 "\"Wise Innocence\" Yanfei (Pyro)"
#define C_72 "\"Dance of the Shimmering Wave\" Eula (Cryo)"
#define C_73 "Memory of Dust (Catalyst)"
#define C_74 "Vortex Vanquisher (Polearm)"
#define C_75 "The Unforged (Claymore)"
#define C_76 "Summit Shaper (Sword)"
#define C_77 "Primordial Jade Cutter (Sword)"
#define C_78 "Staff of Homa (Polearm)"
#define C_79 "Lithic Blade (Claymore)"
#define C_80 "Lithic Spear (Polearm)"
#define C_81 "Elegy of the End (Bow)"
#define C_82 "The Alley Flash (Sword)"
#define C_83 "Wine and Song (Catalyst)"
#define C_84 "Alley Hunter (Bow)"
#define C_85 "Song of Broken Pines (Claymore)"
#define C_86 "\"Scarlet Leaves Pursue Wild Waves\" Kaedehara Kazuha (Anemo)"
#define C_87 "Freedom-Sworn (Sword)"
#define C_88 "Mitternachts Waltz (Bow)"
#define C_89 "\"Frostflake Heron\" Kamisato Ayaka (Cryo)"
#define C_90 "\"Frolicking Flames\" Yoimiya (Pyro)"
#define C_91 "\"Mujina Ninja\" Sayu (Anemo)"
#define C_92 "Mistsplitter Reforged (Sword)"
#define C_93 "Thundering Pulse (Bow)"
#define C_94 "\"Pearl of Wisdom\" Sangonomiya Kokomi (Hydro)"
#define C_95 "\"Crowfeather Kaburaya\" Kujo Sara (Electro)"
#define C_96 "\"Plane of Euthymia\" Raiden Shogun (Electro)"
#define C_97 "Engulfing Lightning (Polearm)"
#define C_98 "Everlasting Moonglow (Catalyst)"
#define C_99 "\"Astute Amusement\" Yae Miko (Electro)"
#define C_100 "\"Protector From Afar\" Thoma (Pryo)"
#define C_101 "Polar Star (Bow)"
#define C_102 "Mouun's Moon (Bow)"
#define C_103 "Wavebreaker's Fin (Polearm)"
#define C_104 "Akuoumaru (Claymore)"
#define C_105 "\"Hanamizaka Heroics\" Arataki Itto (Geo)"
#define C_106 "\"Canine Warrior\" Gorou (Geo)"
#define C_107 "Redhorn Stonethresher (Claymore)"
#define C_108 "\"Stage Lucida\" Yun Jin (Geo)"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
#define C_109 "\"Lonesome Transcendence\" Shenhe (Cryo)"
#define C_110 "Calamity Queller (Polearm)"
#define C_111 "Kamisato Ayato (Hydro)"
#define C_112 "Kagura's Verity (Catalyst)"
#define X_0 "Keqing"
#define X_1 "Mona"
#define X_2 "Qiqi"
#define X_3 "Diluc"
#define X_4 "Jean"
#define X_5 "Amos' Bow"
#define X_6 "Skyward Harp"
#define X_7 "Lost Prayer to the Sacred Winds"
#define X_8 "Skyward Atlas"
#define X_9 "Primordial Jade Winged-Spear"
#define X_10 "Skyward Spine"
#define X_11 "Wolf's Gravestone"
#define X_12 "Skyward Pride"
#define X_13 "Skyward Blade"
#define X_14 "Aquila Favonia"
#define X_15 "Rosaria"
#define X_16 "Xinyan"
#define X_17 "Sucrose"
#define X_18 "Diona"
#define X_19 "Chongyun"
#define X_20 "Noelle"
#define X_21 "Bennett"
#define X_22 "Fischl"
#define X_23 "Ningguang"
#define X_24 "Xingqiu"
#define X_25 "Beidou"
#define X_26 "Xiangling"
#define X_27 "Amber"
#define X_28 "Razor"
#define X_29 "Kaeya"
#define X_30 "Barbara"
#define X_31 "Lisa"
#define X_32 "Rust"
#define X_33 "Sacrificial Bow"
#define X_34 "The Stringless"
#define X_35 "Favonius Warbow"
#define X_36 "Eye of Perception"
#define X_37 "Sacrificial Fragments"
#define X_38 "The Widsith"
#define X_39 "Favonius Codex"
#define X_40 "Favonius Lance"
#define X_41 "Dragon's Bane"
#define X_42 "Rainslasher"
#define X_43 "Sacrificial Greatsword"
#define X_44 "The Bell"
#define X_45 "Favonius Greatsword"
#define X_46 "Lion's Roar"
#define X_47 "Sacrificial Sword"
#define X_48 "The Flute"
#define X_49 "Favonius Sword"
#define X_50 "Slingshot"
#define X_51 "Sharpshooter's Oath"
#define X_52 "Raven Bow"
#define X_53 "Emerald Orb"
#define X_54 "Thrilling Tales of Dragon Slayers"
#define X_55 "Magic Guide"
#define X_56 "Black Tassel"
#define X_57 "Debate Club"
#define X_58 "Bloodtainted Greatsword"
#define X_59 "Ferrous Shadow"
#define X_60 "Skyrider Sword"
#define X_61 "Harbinger of Dawn"
#define X_62 "Cool Steel"
#define X_63 "Venti"
#define X_64 "Klee"
#define X_65 "Tartaglia"
#define X_66 "Zhongli"
#define X_67 "Albedo"
#define X_68 "Ganyu"
#define X_69 "Xiao"
#define X_70 "Hu Tao"
#define X_71 "Yanfei"
#define X_72 "Eula"
#define X_73 "Memory of Dust"
#define X_74 "Vortex Vanquisher"
#define X_75 "The Unforged"
#define X_76 "Summit Shaper"
#define X_77 "Primordial Jade Cutter"
#define X_78 "Staff of Homa"
#define X_79 "Lithic Blade"
#define X_80 "Lithic Spear"
#define X_81 "Elegy of the End"
#define X_82 "The Alley Flash"
#define X_83 "Wine and Song"
#define X_84 "Alley Hunter"
#define X_85 "Song of Broken Pines"
#define X_86 "Kaedehara Kazuha"
#define X_87 "Freedom-Sworn"
#define X_88 "Mitternachts Waltz"
#define X_89 "Kamisato Ayaka"
#define X_90 "Yoimiya"
#define X_91 "Sayu"
#define X_92 "Mistsplitter Reforged"
#define X_93 "Thundering Pulse"
#define X_94 "Sangonomiya Kokomi"
#define X_95 "Kujo Sara"
#define X_96 "Raiden Shogun"
#define X_97 "Engulfing Lightning"
#define X_98 "Everlasting Moonglow"
#define X_99 "Yae Miko"
#define X_100 "Thoma"
#define X_101 "Polar Star"
#define X_102 "Mouun's Moon"
#define X_103 "Wavebreaker's Fin"
#define X_104 "Akuoumaru"
#define X_105 "Arataki Itto"
#define X_106 "Gorou"
#define X_107 "Redhorn Stonethresher"
#define X_108 "Yun Jin"
#define X_109 "Shenhe"
#define X_110 "Calamity Queller"
#define X_111 "Kamisato Ayato"
#define X_112 "Kagura's Verity"
#define E_1 "Unexpected kind! Error code: 1"
#define E_2 "Unexpected fate_weapon! Error code: 2"
#define E_3 "Unexpected resultt! Error code: 3"
#define E_4 "Unexpected resultu! Error code: 4"
#define E_5 "Unexpected chosen_event! Error code: 5"
#define E_6 "Unexpected quit! Error code: 6"
#define E_7 "Unexpected chosen_banner! Error code: 7"
#define E_8 "Unexpected five_count! Error code: 8"
#define E_11 "Arguments error! Usage: chosen_banner chosen_event wishes_number"
#endif