name: ActionsBuilder

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: build
        run: |
          git submodule update --init
          g++ -s -o3 main.cpp lib/giwscli.cpp lib/random_gen.cpp -o giwsfo
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "giwsfo"
          tag: "actions-build"
          token: ${{ secrets.GITHUB_TOKEN }}
